services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    rootDir: backend
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false

  - type: static
    name: react-frontend
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
