services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DB_HOST
        value: bibgroup.cloud
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: rootroot
      - key: DB_NAME
        value: u341164330_email_checker
